<?php

namespace AppBundle\Repository;

/**
 * DogadjajRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogadjajRepository extends \Doctrine\ORM\EntityRepository
{
}
