<?php

namespace AppBundle\Repository;

/**
 * KategorijaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KategorijaRepository extends \Doctrine\ORM\EntityRepository
{
}
