<?php

namespace AppBundle\Repository;

/**
 * KomentarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KomentarRepository extends \Doctrine\ORM\EntityRepository
{
}
