<?php

namespace AppBundle\Repository;

/**
 * PrijavaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrijavaRepository extends \Doctrine\ORM\EntityRepository
{
}
