<?php

namespace AppBundle\Repository;

/**
 * RadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadRepository extends \Doctrine\ORM\EntityRepository
{
}
