<?php

namespace AppBundle\Repository;

/**
 * SmotraRadovaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmotraRadovaRepository extends \Doctrine\ORM\EntityRepository
{
}
