<?php

namespace AppBundle\Repository;

/**
 * SrednjoskolacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SrednjoskolacRepository extends \Doctrine\ORM\EntityRepository
{
}
