<?php

namespace AppBundle\Repository;

/**
 * TakmicenjeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TakmicenjeRepository extends \Doctrine\ORM\EntityRepository
{
}
