<?php

namespace AppBundle\Repository;

/**
 * TimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimRepository extends \Doctrine\ORM\EntityRepository
{
}
